### ISSUE TITLE
Migrate causes error

### ISSUE THREAD

**Issue by mattems** [writingink/wink#10]
When i migrate i get the following error:

```
Migrating: 2018_10_30_000000_create_tables
Migrated:  2018_10_30_000000_create_tables
PHP Warning:  Uncaught ErrorException: Object of class Ramsey\Uuid\Codec\StringCodec could not be converted to string in /Users/matt/www/elevio-website/vendor/laravel/telescope/src/Watchers/ModelWatcher.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(4096, 'Object of class...', '/Users/matt/www...', 35, Array)
#1 /Users/matt/www/elevio-website/vendor/laravel/telescope/src/Watchers/ModelWatcher.php(35): implode('_', Array)
#2 /Users/matt/www/elevio-website/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(357): Laravel\Telescope\Watchers\ModelWatcher->recordAction('eloquent.create...', Array)
#3 /Users/matt/www/elevio-website/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.create...', Array)
#4 /Users/matt/www/elevio-website/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(162): Illuminate\Events\Dispatcher->dispatch('eloquent.create...' in /Users/matt/www/elevio-website/vendor/laravel/telescope/src/Watchers/ModelWatcher.php on line 35
PHP Fatal error:  Object of class Ramsey\Uuid\Converter\Number\BigNumberConverter could not be converted to string in /Users/matt/www/elevio-website/vendor/laravel/telescope/src/Watchers/ModelWatcher.php on line 35

   Symfony\Component\Debug\Exception\FatalErrorException  : Object of class Ramsey\Uuid\Converter\Number\BigNumberConverter could not be converted to string

  at /Users/matt/www/elevio-website/vendor/laravel/telescope/src/Watchers/ModelWatcher.php:35
    31|         if (! $this->shouldRecord($event)) {
    32|             return;
    33|         }
    34| 
  > 35|         $model = get_class($data[0]) . ':' . implode('_', (array) $data[0]->getKey());
    36| 
    37|         $changes = $data[0]->getChanges();
    38| 
    39|         Telescope::recordModelEvent(IncomingEntry::make(array_filter([


   Whoops\Exception\ErrorException  : Object of class Ramsey\Uuid\Converter\Number\BigNumberConverter could not be converted to string

  at /Users/matt/www/elevio-website/vendor/laravel/telescope/src/Watchers/ModelWatcher.php:35
    31|         if (! $this->shouldRecord($event)) {
    32|             return;
    33|         }
    34| 
  > 35|         $model = get_class($data[0]) . ':' . implode('_', (array) $data[0]->getKey());
    36| 
    37|         $changes = $data[0]->getChanges();
    38| 
    39|         Telescope::recordModelEvent(IncomingEntry::make(array_filter([

```

**Comment by themsaid** [comment]
this should be resolved now
